### ISSUE TITLE
How to retrieve popcode address from its private key?

### ISSUE THREAD

**Issue by xraywu** [thingchain/nodejs-api#2]
Just wondering if there is an API/SDK method for retrieving a popcode's master address from its private key? Since when someone wish to possess a thing the only token he will have will be the private key shipped in QR code. Tried the `search` method with a couple queries but no luck hitting the thing I created... Thanks.

**Comment by rushilr** [comment]
Here's how you get the key:

```
var priv_key = new bitcore.PrivateKey(popcode_private_key);
console.log(priv_key.toAddress().toString())
```
